# Generated by Django 4.1.6 on 2023-02-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_store_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=30)),
                ('contactno', models.IntegerField()),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
